[package]
name = "stepler-cli"
version = "1.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde_json = "1"
stepler-app = { path = "../stepler-app" }
stepler-core = { path = "../stepler-core" }
stepler-platform = { path = "../stepler-platform" }
stepler-platform-windows = { path = "../stepler-platform-windows" }
